### ISSUE TITLE
Build error on master: ‘struct Hantek::ControlSpecification’ has no member named ‘gainDiv’

### ISSUE THREAD

**Issue by drothlis** [OpenHantek/openhantek#26]
Build error introduced in fc04859:

```
openhantek/src/hantek/control.cpp: In member function ‘virtual void Hantek::Control::connectDevice()’:
openhantek/src/hantek/control.cpp:943:25: error: ‘struct Hantek::ControlSpecification’ has no member named ‘gainDiv’
     this->specification.gainDiv
                         ^
```

May I humble suggest raising pull requests even for your own commits, to give Travis a chance to compile-test it?
