### PR TITLE
Openglfixes

### PR DESCRIPTION
**Pull request by coozoo**
This pull request for this issue

[error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES](https://github.com/OpenHantek/openhantek/issues/221).

### CODE REVIEW

File: openhantek/src/main.cpp [hunk 1]
```diff
@@ -92,15 +92,15 @@ int main(int argc, char *argv[]) {
 #endif
 
     bool useGles = false;
-    {
+    if(useGles) {
```
Comment (davidgraeff) [inline openhantek/src/main.cpp]: That looks absolutely wrong. It is dead code now

File: openhantek/src/glscope.cpp [hunk 2]
```diff
@@ -40,15 +40,15 @@ void GlScope::fixOpenGLversion(QSurfaceFormat::RenderableType t) {
     // Prefer full desktop OpenGL without fixed pipeline
     QSurfaceFormat format;
     format.setSamples(4); // Antia-Aliasing, Multisampling
-    format.setProfile(QSurfaceFormat::CoreProfile);
     if (t==QSurfaceFormat::OpenGLES) {
-        format.setVersion(2, 0);
```
Comment (davidgraeff) [inline openhantek/src/glscope.cpp]: The version restrictions don't mean the exact version but a minimum required version. And it will not work with OpenGL es 1.0

File: openhantek/src/main.cpp (hunk 1 above)
Comment (coozoo) [reply openhantek/src/main.cpp]: Agree, that's ugly. But it was more wrong :)
This part between curly brackets all the time returned true
``` c++
useGles = p.isSet(useGlesOption);
```
and without if in any case I felt into this part:
``` c++
bool useGles = false;
{
....
}
```
and as result youend up with useGles=true and fall into openGL mode

Comment (davidgraeff) [reply openhantek/src/main.cpp]: It is not just ugly it disables the command line parsing completly. The behaviour was submitted by a user with the argument that the command line argument should always overwrite the auto detection. And yes OpenGL es ist the preferred render engine if both are detected.

File: openhantek/src/glscope.cpp (hunk 2 above)
Comment (coozoo) [reply openhantek/src/glscope.cpp]: Actually OpenGL ES 1.0 doesn't work in the way how it's written in the code

``` c++
   const char *vshaderES = R"(
           #version 100
            attribute highp vec3 vertex;
            uniform mat4 matrix;
            void main()
            }
      )";
```

It will tell you about compilation error you need to define precision in vertex (something like that)
when you define precision it throws to another error

that's why I've changed version to 1.2
```
 #version 120
```
I agree it's not good solution to increase version, but I didn't find solution
Sure maybe you know because my experience in OpenGL just one day :)

File: openhantek/src/main.cpp (hunk 1 above)
Comment (coozoo) [reply openhantek/src/main.cpp]: oh yes I've  sorry I've did stupid thing because usually used getopt
and misunderstood qt doc ) 
actually it works like it should. But yes that' what I thought that auto detection should be there )
So yes you are right I've did stupid thing here

File: openhantek/src/glscope.cpp [hunk 3]
```diff
@@ -196,14 +196,15 @@ void GlScope::initializeGL() {
           }
     )";
     const char *fshaderES = R"(
-          #version 100
+          #version 120
```
Comment (davidgraeff) [inline openhantek/src/glscope.cpp]: Doesn't make sense this way :/ Open GL ES shader versions are listed here: https://github.com/mattdesl/lwjgl-basics/wiki/glsl-versions#glsl-es-versions-android-ios-webgl. There is no "120".

**Comment by coozoo** [comment]
Yes you are right revert opengl es. But actually can't guess how it works. Can't explain why I've received duch error. And rechecked  opengles and opengl for me works fine. So actually here now only fix for opengl like my intel card.

File: openhantek/src/glscope.cpp [hunk 4]
```diff
@@ -212,10 +213,13 @@ void GlScope::initializeGL() {
...
     const char *fshaderDesktop = R"(
-          #version 150
+          #version 120
           uniform highp vec4 colour;
-          out vec4 flatColor;
-          void main() { flatColor = colour; }
+          //out vec4 flatColor;
+          void main()
+          {
+          gl_FragColor = colour;
```
Comment (davidgraeff) [inline openhantek/src/glscope.cpp]: See https://www.opengl.org/discussion_boards/showthread.php/184313-where-has-built-in-variable-gl_FragColor-gone-in-OpenGL-4-4?s=4da3cf47b4e9c44fa1c55d2e63528b85&p=1259897&viewfull=1#post1259897

gl_FragColor is deprecated and I rather not use it here to just support super old graphic stacks. Those old stacks can use the OpenGL ES 2.0 render path instead.

File: openhantek/src/glscope.cpp [hunk 5]
```diff
@@ -200,10 +200,11 @@ void GlScope::initializeGL() {
...
           void main() { gl_FragColor = colour; }
     )";
-
+    
     const char *vshaderDesktop = R"(
-          #version 150
-          in highp vec3 vertex;
+          #version 120
+          //in highp vec3 vertex;
+          attribute vec3 vertex;
```
Comment (davidgraeff) [inline openhantek/src/glscope.cpp]: See https://github.com/vispy/vispy/issues/242
"attribute" is deprecated, "in" and "out" should be used.

Comment (coozoo) [reply openhantek/src/glscope.cpp]: Deprecated in language 1.5 but not in 1.2 :) and as i've understood openGL even 4.0 still support  old versions of languages.
Yes old  but actually a lot of such old laptops used in labs )
And I don't see the tech limitations do not support  language
But who is a doctor here ) ok closing

**Comment by coozoo** [comment]
Doctor Rejected to lower shading language version :)
